on:
  push:
    branches:
      - main
name: Raisely Deploy Staging
env:
  CAMPAIGN_NAME: ${{ secrets.RAISELY_CAMPAIGN_NAME }}
jobs:
  raiselyDeploy:
    name: Raisely Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://living-sober.raisely.com/
    steps:
    - uses: actions/checkout@v2
    - name: Create folder 
      run: mkdir stylesheets
    - name: Move and Rename styles folder 
      run: mv campaign-styles stylesheets/$CAMPAIGN_NAME 
    - name: Rename file 
      run:  mv stylesheets/$CAMPAIGN_NAME/custom-styles.scss stylesheets/$CAMPAIGN_NAME/$CAMPAIGN_NAME.scss
    - name: Raisely Deploy
      uses: raisely/deploy@v1
      with:
        campaign: ${{ secrets.RAISELY_CAMPAIGN_UUID }}
        apikey: ${{ secrets.RAISELY_API_KEY }}