on:
  push:
    branches: 
      - staging
name: Deploy Staging
jobs:
  raiselyDeploy:
    name: Raisely Deploy Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://living-sober-dev.raisely.com/
    steps:
    - uses: actions/checkout@v2
    - name: Create folder
      run: mkdir stylesheets
    - name: Move and Rename styles folder
      run: mv campaign-styles stylesheets/living-sober-dev
    - name: Rename file 
      run:  mv stylesheets/living-sober-dev/custom-styles.scss stylesheets/living-sober-dev/living-sober-dev.scss
    - name: Raisely Deploy
      uses: raisely/deploy@v1
      with:
        campaign: ${{ secrets.RAISELY_CAMPAIGN_UUID }}
        apikey: ${{ secrets.RAISELY_API_KEY }}