on:
  push:
    branches: 
      - staging
name: Deploy Staging
jobs:
  raiselyDeploy:
    name: Raisely Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Raisely Deploy
      uses: raisely/deploy@v1
      with:
        campaign: ${{ secrets.RAISELY_CAMPAIGN_UUID_DEV }}
        apikey: ${{ secrets.RAISELY_API_KEY_DEV }}