on: 
  push:
    branches:
      - staging
name: Raisely Deploy Staging
jobs:
  raiselyDeploy:
    name: Raisely Deploy
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://living-sober-dev.raisely.com/
    steps:
    - uses: actions/checkout@v2
    - name: Creat folder 
      run: mkdir stylesheets
    - name: Move and Rename styles folder 
      run: mv campaign-styles stylesheets/livingsober-dev 
    - name: Rename file 
      run:  mv stylesheets/livingsober-dev/campaign-styles.scss stylesheets/livingsober-dev/livingsober.scss
    - name: Raisely Deploy
      uses: raisely/deploy@v1
      with:
        campaign: ${{ secrets.RAISELY_CAMPAIGN_STAGING }}
        apikey: ${{ secrets.RAISELY_API_KEY_STAGING }}