on:
  pull_request:
    branches: 
      - main
    types: [closed]
name: Deploy Production
jobs:
  raiselyDeploy:
    name: Raisely Deploy Production
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Create folder 
      run: mkdir stylesheets
    - name: Move and Rename styles folder 
      run: mv campaign-styles stylesheets/living-sober
    - name: Rename file 
      run:  mv stylesheets/living-sober/custom-styles.scss stylesheets/living-sober/living-sober.scss
    - name: Raisely Deploy
      uses: raisely/deploy@v1
      with:
        campaign: ${{ secrets.RAISELY_CAMPAIGN_UUID_PROD }}
        apikey: ${{ secrets.RAISELY_API_KEY_PROD }}