on:
  push:
    branches:
      - main
name: Raisely Deploy
jobs:
  raiselyDeploy:
    name: Raisely Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://living-sober.raisely.com/
    steps:
    - uses: actions/checkout@v2
    - name: Raisely Deploy
      uses: raisely/deploy@v1
      with:
        campaign: ${{ secrets.RAISELY_CAMPAIGN_PRODUCTION }}
        apikey: ${{ secrets.RAISELY_API_KEY_PRODUCTION }}